### ISSUE TITLE
Can we use nopecha in Selenium headless mode?

### ISSUE THREAD

**Issue by aliraza-es** [NopeCHALLC/nopecha-python#2]

**Comment by oyunvfg** [comment]
I think I was scammed. I wish I had read this before.

**Comment by NopeCHALLC** [comment]
Yes, both the [Chrome extension](https://nopecha.com/chrome) and [Firefox Add-on](https://nopecha.com/firefox) works with Selenium and all other browser automation tools.

Please refer to the [documentation and guide](https://developers.nopecha.com/) for more information.
