### ISSUE TITLE
Times out after 10 retries

### ISSUE THREAD

**Issue by Psekk** [NopeCHALLC/nopecha-python#7]
After using the token solve api via this extension it returns a timed out after 10 retries. It shows up in the activity monitor but doesn't get past the POST, it returns the data of the POST and gets stuck at the GET nor does it show the GET in the activity monitor leaving me to believe it's an API issue and not an extension. I have no idea where else to report this issue however.

**Comment by codewc** [comment]
I have the same issue. 

# Call the Token API
token = nopecha.Token.solve(
    type='turnstile',
    sitekey='0x4AAAAAAAWDqqyICyGsIG43',
    url='https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/b/turnstile/if/ov2/av0/rcv0/0/lcxw5/0x4AAAAAAAWDqqyICyGsIG43/dark/normal/auto/',
    useragent=useragent,
)
logger.info(token)

> After using the token solve api via this extension it returns a timed out after 10 retries. It shows up in the activity monitor but doesn't get past the POST, it returns the data of the POST and gets stuck at the GET nor does it show the GET in the activity monitor leaving me to believe it's an API issue and not an extension. I have no idea where else to report this issue however.

I have the same issule. 
    token = nopecha.Token.solve(
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/miniconda3/envs/reverse/lib/python3.12/site-packages/nopecha/_v1_compat.py", line 19, in solve
    return client.solve_raw(typing.cast(TokenRequest, kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/miniconda3/envs/reverse/lib/python3.12/site-packages/nopecha/api/_base.py", line 160, in solve_raw
    return self._request(f"{self.host}/token/", body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/miniconda3/envs/reverse/lib/python3.12/site-packages/nopecha/api/_base.py", line 119, in _request
    job_id = self._request_post(endpoint, body)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/miniconda3/envs/reverse/lib/python3.12/site-packages/nopecha/api/_base.py", line 135, in _request_post
    raise RuntimeError(
RuntimeError: Server did not accept job after 10 attempts. Server may be overloaded (https://nopecha.com/discord). Alternatively try increasing the post_max_attempts parameter (or set to 0 for unlimited retries).

**Comment by Le0Developer** [comment]
No you don't. You are using the legacy V1 compat layer which doesn't support setting the subscription key the way you are doing. Read the README.

**Comment by Le0Developer** [comment]
> After using the token solve api via this extension it returns a timed out after 10 retries. It shows up in the activity monitor but doesn't get past the POST, it returns the data of the POST and gets stuck at the GET nor does it show the GET in the activity monitor leaving me to believe it's an API issue and not an extension. I have no idea where else to report this issue however.

https://nopecha.com/discord for support.
